[project]
name = "mapfemrs"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "ruff>=0.15.0",
]


[tool.ruff]
line-length=79

[tool.ruff.lint]
select=['I', 'F', 'E', 'W', 'PL', 'PT']

[tool.ruff.format]
quote-style='single'
indent-style='space'
docstring-code-format=true
docstring-code-line-length=30

[tool.pytest.ini_options]
pythonpath = '.'
addopts = '-p no:warnings'
